#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

# Copyright © 2021 Chindraba (Ronald Lamoreaux)
#                 <httpd-config@chindraba.work>

fqdn="$1"
tld="${fqdn##*.}"
temp="${fqdn%.$tld}"
domain="${temp##*.}"
host="${temp%.$domain}"

mkdir -p /content/sites/$tld/$domain/$host/{cgi-bin,htdocs}

printf "Use DefDefaultHost %s %s.%s %s/%s/%s\n\n# vim: syntax=sh ts=4 sw=4 sts=4 et sr" \
    $host $domain $tld \
    $tld $domain $host >"/etc/httpd/sites_available/$tld.$domain.$host.vhost.ssl.conf"

[ -f "/content/sites/$tld/$domain/$host/htdocs/index.html" ] || \
    perl -p -e "s/<<HOST>>/$host/g; s/<<DOMAIN>>/$domain/g; s/<<TLD>>/$tld/g;" \
        < "/etc/httpd/sites_available/__index.html"\
        > "/content/sites/$tld/$domain/$host/htdocs/index.html"

# vim: syntax=sh ts=4 sw=4 sts=4 et sr
