#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

# Copyright © 2021 Chindraba (Ronald Lamoreaux)
#                 <httpd-config@chindraba.work>

fqdn="$1"
tld="${fqdn##*.}"
temp="${fqdn%.$tld}"
domain="${temp##*.}"
host="${temp%.$domain}"

rm -rf "/etc/httpd/sites_enabled/$tld.$domain.$host.vhost.*"
systemctl restart httpd

# vim: syntax=sh ts=4 sw=4 sts=4 et sr
